### ISSUE TITLE
Step files for v1r3

### ISSUE THREAD

**Issue by gniezen** [iorodeo/open_colorimeter_enclosure#1]
Hi @willdickson ! :smile: 

I noticed that in `step/v1r3/` there is a `pybadge_cover_v1r3.step` and a `pybadgecoverv1r3.step`. Are these the same file? There's also no `colorimeter_enclosure_v1r3.step` - is the intention to use `colorimeter_enclosure_v1r2.step`, but with the cover in this folder?

**Comment by iorodeo** [comment]
Yes,  the two pybadge cover .step files in v1r3 are the same.  There was a brief time where a 3D printing service were using had a temporary bug in its file upload such that it wouldn't accept files names with underscores.  This is a left over from that -  sorry for the confusion.  I'll remove the version without the underscores.  

The latest version of the colorimeter enclosure is in v1r2.  The weren't any changes to the enclosure in the v1r3 revision. I  made some changes to the pybadge cover to have better clearance near the display.  Some batches of the pybadge can have a little bit of glue on the pcb near the display.  If you don't have the extra clearance the cover won't sit flush.  It might be less confusing if I included a .step version of the enclosure in with the v1r3 step files so that it contains a complete set of files - even if it is unchanged in this revision.

**Comment by gniezen** [comment]
Thanks Will, I see you've already made the update in df89879
